## 1. Create a null vector of size 10 but the fifth value which is 1.

In [24]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

# Set the fifth value to 1
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [25]:
vector_10_to_49 = np.arange(10, 49)

print(vector_10_to_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [29]:
# Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)

print(non_zero_indices)


(array([0, 1, 4], dtype=int64),)


## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [30]:
# Create a 10x10 array with random values
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array_10x10)
max_value = np.max(random_array_10x10)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.026218656981996435
Maximum value: 0.9853816679666267


## 6. Create a random vector of size 30 and find the mean value.

In [31]:
# Create a random vector of size 30
random_vector_size = np.random.random(30)

# Find the mean value
mean_value = np.mean(random_vector_size)

print("Random Vector:", random_vector_size)
print("Mean value:", mean_value)

Random Vector: [0.90894217 0.36135841 0.8063139  0.83417544 0.63006164 0.22105055
 0.67380476 0.20932396 0.45133741 0.6808756  0.41338467 0.21299023
 0.36503883 0.85091181 0.27694803 0.41664074 0.94259545 0.43867397
 0.44081039 0.4433687  0.85998208 0.93219684 0.87736332 0.68055975
 0.76189567 0.13228717 0.86296424 0.60949802 0.95199442 0.77572808]
Mean value: 0.600769208791796
